version = "0.1"

[assemblers]
gas = true
go = true
z80 = true
masm = true
nasm = true

[instruction_sets]
x86 = true
x86_64 = true
z80 = false
arm = true
riscv = false

[opts]
# compiler = "gcc"
diagnostics = true
default_diagnostics = true
