version = "0.1"

[assemblers]
gas = true
go = false
z80 = false
masm = false
nasm = true

[instruction_sets]
x86 = true
x86_64 = true
z80 = false
arm = false
riscv = false

[opts]
compiler = "clang"
diagnostics = true
default_diagnostics = true
