[Work]
source        = imaps://autumnroman1997%40gmail.com:WaRaTan0Rfd3L658@imap.gmail.com:993
outgoing      = smtps://autumnroman1997%40gmail.com:WaRaTan0Rfd3L658@smtp.gmail.com:587
default       = INBOX
from          = "Autumn Roman" <autumnroman1997@gmail.com>
copy-to       = /home/le/.local/aerc/sent-mail
cache-headers = true
