#!/bin/bash

for i in 1 2 3 4 5 6;
do
	
tty=$(w | grep tty | awk '{print $2}' | sed -n "$i"p)

ttyS=$(echo "$tty" | python ~/.scripts/tty_filter/tty_filter.py)
ttyN=$((ttyS))
echo "$ttyT"

	if [ $i -ne "$ttyN" ]; then

		ttyW=$i
		sudo chvt "$ttyW"
		exit

	fi
done

echo "No new shells available :'("

exit