[Custom]
ColorTheme=Wonton Soup
Language=
StyleTheme=

[Defaults]
PresetPreview=false
SoundFontDir=

[Engine]
Qsynth2\Presets\DefPreset=(default)
Qsynth2\Settings\AlsaName=Qsynth2
Qsynth2\Settings\AudioBufCount=2
Qsynth2\Settings\AudioBufSize=64
Qsynth2\Settings\AudioChannels=2
Qsynth2\Settings\AudioDevice=
Qsynth2\Settings\AudioDriver=alsa
Qsynth2\Settings\AudioGroups=1
Qsynth2\Settings\ChorusActive=true
Qsynth2\Settings\ChorusDepth=8
Qsynth2\Settings\ChorusLevel=1
Qsynth2\Settings\ChorusNr=3
Qsynth2\Settings\ChorusSpeed=0.30000001192092896
Qsynth2\Settings\ChorusType=0
Qsynth2\Settings\DisplayName=Qsynth2
Qsynth2\Settings\Gain=1
Qsynth2\Settings\JackAutoConnect=true
Qsynth2\Settings\JackMulti=false
Qsynth2\Settings\JackName=Qsynth2
Qsynth2\Settings\LadspaActive=false
Qsynth2\Settings\MidiAutoConnect=true
Qsynth2\Settings\MidiBankSelect=gm
Qsynth2\Settings\MidiChannels=16
Qsynth2\Settings\MidiDevice=
Qsynth2\Settings\MidiDriver=alsa_seq
Qsynth2\Settings\MidiDump=false
Qsynth2\Settings\MidiIn=true
Qsynth2\Settings\Polyphony=256
Qsynth2\Settings\ReverbActive=true
Qsynth2\Settings\ReverbDamp=0
Qsynth2\Settings\ReverbLevel=0.8999999761581421
Qsynth2\Settings\ReverbRoom=0.20000000298023224
Qsynth2\Settings\ReverbWidth=0.5
Qsynth2\Settings\SampleFormat=16bits
Qsynth2\Settings\SampleRate=44100
Qsynth2\Settings\Server=false
Qsynth2\Settings\Verbose=false
Qsynth2\Settings\WasapiExclusive=false

[Engines]
Engine1=Qsynth2

[Geometry]
qsynthChannelsForm\geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x1c\0\0\x1\"\0\0\x4#\0\0\x2\x61\0\0\x2\x1c\0\0\x1\"\0\0\x4#\0\0\x2\x61\0\0\0\0\x2\0\0\0\x6@\0\0\x2\x1c\0\0\x1\"\0\0\x4#\0\0\x2\x61)
qsynthChannelsForm\visible=false
qsynthMainForm\geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x34\0\0\x6?\0\0\x3\x83\0\0\x1\xa9\0\0\x1\x62\0\0\x4\xbd\0\0\x2#\0\0\0\0\x2\0\0\0\x6@\0\0\0\0\0\0\0\x34\0\0\x6?\0\0\x3\x83)
qsynthMainForm\visible=true
qsynthMessagesForm\geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x1c\0\0\x1J\0\0\x4#\0\0\x2\x39\0\0\x2\x1c\0\0\x1J\0\0\x4#\0\0\x2\x39\0\0\0\0\x2\0\0\0\x6@\0\0\x2\x1c\0\0\x1J\0\0\x4#\0\0\x2\x39)
qsynthMessagesForm\visible=false

[History]
MessagesLogPathComboBox\Item1=qsynth.log

[Options]
BaseFontSize=0
KeepOnTop=false
KnobMotion=1
KnobStyle=1
MessagesFont="Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
MessagesLimit=true
MessagesLimitLines=1000
MessagesLog=false
MessagesLogPath=qsynth.log
OutputMeters=false
QueryClose=true
StartMinimized=false
StdoutCapture=true
SystemTray=false
SystemTrayQueryClose=true

[Presets]
DefPreset=(default)

[Program]
Version=0.9.12

[Settings]
AlsaName=pid
AudioBufCount=2
AudioBufSize=64
AudioChannels=1
AudioDevice=
AudioDriver=jack
AudioGroups=1
ChorusActive=true
ChorusDepth=8
ChorusLevel=1
ChorusNr=3
ChorusSpeed=0.30000001192092896
ChorusType=0
DisplayName=Qsynth1
Gain=1
JackAutoConnect=true
JackMulti=false
JackName=qsynth
LadspaActive=false
MidiAutoConnect=true
MidiBankSelect=gm
MidiChannels=16
MidiDevice=
MidiDriver=alsa_seq
MidiDump=false
MidiIn=true
Polyphony=256
ReverbActive=true
ReverbDamp=0
ReverbLevel=0.8999999761581421
ReverbRoom=0.30000001192092896
ReverbWidth=0.5
SampleFormat=16bits
SampleRate=44100
Server=false
Verbose=false
WasapiExclusive=false
