[General]
firstTime=false
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x6\x37\0\0\x3J\0\0\0\0\0\0\0\0\0\0\x6\x37\0\0\x3J\0\0\0\0\0\0\0\0\x6@\0\0\0\0\0\0\0\0\0\0\x6\x37\0\0\x3J)
geometryNomacs=@Rect(0 0 1592 843)
windowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x6\x38\0\0\x3\x19\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\0\0\0\x16\0\x45\0\x64\0i\0t\0T\0o\0o\0l\0\x42\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[AppSettings]
appMode=0
currentAppMode=0
defaultJpgQuality=97
firstTime.nomacs.3=false
showPlayer=@Variant(\0\0\0\r\0\0\0\x6\x1)

[DisplaySettings]
bgColorNoMacsRGBA=4293914607
bgColorWidgetRGBA=1711276032
iconColorRGBA=4281545523

[DkAppManager]
Apps\size=0

[DkFilePreview]
windowPosition=1

[DkMetaDataHUD]
keyValues=File.Filename, File.Path, File.Size, Exif.Image.Make, Exif.Image.Model, Exif.Image.DateTime, Exif.Image.ImageDescription, Exif.Photo.ISO, Exif.Photo.FocalLength, Exif.Photo.ExposureTime, Exif.Photo.Flash, Exif.Photo.FNumber
numColumns=-1
windowPosition=3

[GlobalSettings]
lastDir=/home/le/Pictures/Wallpapers
recentFiles=/home/le/Pictures/Wallpapers/undefined - Imgur(1).jpg, /home/le/Pictures/Wallpapers/Live/sunset-rooftop-pool.gif, /home/le/Pictures/Wallpapers/Live/sparkling-beach.gif, /home/le/Pictures/Wallpapers/Live/ultra-necrozma.gif, /home/le/Pictures/Wallpapers/Live/raining-stars.gif, /home/le/Pictures/Wallpapers/Live/dodge-demon.gif, /home/le/Pictures/Wallpapers/ultra-necrozma.gif, /home/le/Pictures/Wallpapers/raining-stars.gif, /home/le/Pictures/Wallpapers/cyberpunk-night-dream.gif, /home/le/Pictures/Wallpapers/color-black-hole-1.gif, /home/le/Downloads/backiee-248192-landscape.jpg, "/home/le/Downloads/HUAWEI MateBook X Pro 2019 User Guide-(01,en-us,MACHR,RS5,SI).pdf", "/home/le/Downloads/Poularikas, Alexander D. - Understanding Digital Signal Processing with MATLAB® and Solutions. (2017, CRC Press) - libgen.li.pdf", /home/le/Downloads/backiee-84460-landscape.jpg, /home/le/.local/share/icons/Skyrim/Skyrim.cursor.logo.png, /home/le/.local/share/icons/Skyrim/hand-alt-Solstheim.png, /home/le/.local/share/icons/Skyrim/hand-01.png, /home/le/.local/share/icons/Skyrim/hand-02.png, /home/le/.config/alacritty/alacritty-theme/images/github_dark_default.png, /home/le/.config/alacritty/alacritty-theme/images/github_dark_colorblind.png, /home/le/.config/alacritty/alacritty-theme/images/github_dark.png, /home/le/.config/alacritty/alacritty-theme/images/flexoki.png, /home/le/.config/alacritty/alacritty-theme/images/flat_remix.png, /home/le/odst.gif, /home/le/.cache/swww/eDP-1
recentFolders=/home/le/Pictures/Wallpapers, /home/le/Pictures/Wallpapers/Live, /home/le/Downloads, /home/le/.local/share/icons/Skyrim, /home/le/.config/alacritty/alacritty-theme/images, /home/le, /home/le/.cache/swww

[SynchronizeSettings]
checkForUpdates=true
disableUpdateInteraction=false

[zooming]
useLevels=false
zoomLevels="0.0001,0.001,0.01,0.05,0.1,0.125,0.166,0.25,0.333,0.5,0.66,1,1.5,2,3,4,5,6,7,8,12,16,32,64,128"
