### Output configuration (man 5 sway-output / swaymsg -t get_outputs)
### For a dynamic output configuration take a look at the provided kanshi example

# output eDP-1 pos 0 0 scale 2
#output DP-4 pos 1920 0 res 1920x1080
#output DP-5 pos 3840 0 res 1920x1080

# swaymsg -t get_outputs | jq -r '.[] | .name'
# swaymsg output eDP-1 pos 1920 0 res 1920x1080
# swaymsg output DP-7 pos 3840 0 res 1920x1080

# Disable the laptop screen when the lid is closed.
bindswitch --reload --locked lid:on output eDP-1 disable
bindswitch --reload --locked lid:off output eDP-1 enable

output * bg ~/Pictures/background-images/back1.jpg fill
