workspace_layout tabbed

workspace_auto_back_and_forth yes

# assign program to workspace
assign [class="Firefox"] $ws1
assign [app_id="firefox"] $ws1
assign [app_id="spotify"] $ws11
assign [class="Thunderbird"] $ws12
assign [app_id="thunderbird"] $ws12


# assign workspace to monitor
#workspace $ws1 output eDP-1
#workspace $ws2 output DP-4
#workspace $ws3 output DP-5
