### Input configuration (man 5 sway-input / swaymsg -t get_inputs)

input * {
    xkb_layout mth,ru
    xkb_options {
        "grp:alt_caps_toggle, lv3:ralt_switch, mod_led:compose, caps:backspace, compose:lwin-altgr, nbsp:level3n, shift:both_capslock, keypad:pointerkeys"
    }
    natural_scroll disabled 
    repeat_delay 250
    repeat_rate 36
}

input type:touchpad {
    dwt disabled
    tap disabled
    tap_button_map lrm
    natural_scroll disabled
    drag enabled
    middle_emulation enabled

}

input "1:1:AT_Translated_Set_2_keyboard" {    

}

# input "NAME_OF_MOUSE" {
        # natural_scroll disabled
# }

input "1133:16399:Logitech_K750" {
    xkb_layout us(colemak),us,ru
    repeat_delay 200
    repeat_rate 50
}

input "1267:8400:ELAN_Touchscreen" {
    drag enabled
    events disabled_on_external_mouse
    dwt enabled
    scroll_factor 10.0
    accel_profile adaptive
    pointer_accel 1

}
