# Color vars
set $col_focused #35CE8D
set $col_focused_inactive #EEE82C
set $col_unfocused #7161EF
set $col_text_dark #121420
set $col_text_light #F7F0F0
set $col_urgent #E40066
set $col_unfocused_border #121420

# class                  border                 background             text             indicator              child_border
client.focused           $col_focused           $col_focused           $col_text_dark   $col_focused           $col_focused
client.focused_inactive  $col_focused_inactive  $col_focused_inactive  $col_text_dark   $col_focused_inactive  $col_focused_inactive
client.unfocused         $col_unfocused_border  $col_unfocused         $col_text_light  $col_unfocused         $col_unfocused
client.urgent            $col_text_dark         $col_urgent            $col_text_dark   $col_urgent            $col_urgent

# Titlebar
titlebar_padding 1
title_align center
titlebar_border_thickness 1

# Borders
default_border pixel 1
smart_borders on

# Gaps
smart_gaps on
gaps inner 4
gaps outer 3

# GTK settings
set $gnome-schema org.gnome.desktop.interface

seat seat0 xcursor_theme 'Skyrim' 32
exec_always {
    gsettings set $gnome-schema gtk-theme 'gruvbox-dark-gtk'
    gsettings set $gnome-schema icon-theme 'Gruvbox-Material-Dark'
    gsettings set $gnome-schema cursor-theme 'Skyrim'
    gsettings set $gnome-schema font-name 'Cantarell 13'
}

### Bar
exec_always 'pkill waybar; waybar -c ~/.config/waybar/config; waybar -c ~/.config/waybar/config-bottom'

bar {
    id "bottom"
    swaybar_command "waybar -c ~/.config/waybar/config-bottom"
#    position bottom
#    mode invisible
#    mode hide
#    # modifier $mod
#    # When the status_command prints a new line to stdout, swaybar updates.
#    # The default just shows the current date and time.
#    status_command while date +'%y-%m-%d %i:%m:%s %p'; do sleep 1; done
#    colors {
#        statusline #ffffff
#        background #323232
#
#    }
}
